//
// PPx Version (ppxver.plÇ…ÇÊÇÈé©ìÆê∂ê¨)
//
#ifndef WS_CAPTION // for resource include
#include <windows.h>
#include <winuser.h>
#endif

#define VersionH		1
#define VersionM		7
#define VersionL		2
#define VersionP		0
#define FileProp_Version	"1.72"		// for Propaty sheet
#define FileCfg_Version	"1.72"	// for CFGver
#define X_Version		"1.7.2.0"	// for XML
#define Q_Version		1,7,2,0	// for Quick view
#define COM_ver			Q_Version	// Common
#define BUI_ver			Q_Version	// bUI
#define CUI_ver			Q_Version	// cUI
#define VUI_ver			Q_Version	// vUI
#define ReleaseYear		"2020"
