//
// PPx Version (ppxver.plÇ…ÇÊÇÈé©ìÆê∂ê¨)
//
#ifndef WS_CAPTION // for resource include
#include <windows.h>
#include <winuser.h>
#endif

#define VersionH		1
#define VersionM		6
#define VersionL		6
#define VersionP		0
#define FileProp_Version	"1.66"		// for Propaty sheet
#define FileCfg_Version	"1.66"	// for CFGver
#define X_Version		"1.6.6.0"	// for XML
#define Q_Version		1,6,6,0	// for Quick view
#define COM_ver			Q_Version	// Common
#define BUI_ver			Q_Version	// bUI
#define CUI_ver			Q_Version	// cUI
#define VUI_ver			Q_Version	// vUI
#define ReleaseYear		"2019"
